package com.example.dd2composetest.ui.compose.fakecomponents

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ComposableOpenTarget
import androidx.compose.runtime.ComposableTarget
import androidx.compose.runtime.InternalComposeApi

/**
 * An annotation generated by the compose compiler plugin. Do not use explicitly.
 *
 * The [ComposableInferredTarget] annotation is an abbreviated form of [ComposableTarget] and
 * [ComposableOpenTarget] generated by the compose compiler plugin when it infers the target of a
 * composable function that has one or more composable lambda parameters.
 *
 * This is intended to only be generated by the plugin and should not be used directly. Use
 * [ComposableOpenTarget] and [ComposableTarget] instead.
 *
 * This annotation is used by the Compose compiler plugin because Kotlin compiler plugins are a not
 * allowed to add annotations to types such as the lambda types of a [Composable] function
 * parameter. This annotation records which annotation would have been added.
 */
@InternalComposeApi
@Retention(AnnotationRetention.BINARY)
@Target(
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER,
)
annotation class ComposableInferredTarget(val scheme: String)